import { mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { BuildOutput } from './normalize';

const HEADER = '// AUTO-GENERATED by scripts/sync-github.ts. Do not edit; this folder is gitignored.\n';

/** Builds the lazy loader map so each project README becomes its own code-split chunk. */
export function projectLoadersSource(slugs: readonly string[]): string {
  const entries = [...slugs]
    .sort()
    .map((slug) => `  ${JSON.stringify(slug)}: () => import('./projects/${slug}.json').then((m) => m.default as ProjectDetail),`);
  return (
    HEADER +
    `import type { ProjectDetail } from '../app/data/models';\n\n` +
    `export const PROJECT_LOADERS: Readonly<Record<string, () => Promise<ProjectDetail>>> = {\n` +
    entries.join('\n') +
    `\n};\n`
  );
}

/** Writes the generated data the Angular app imports at build time. */
export async function writeOutputs(dir: string, output: BuildOutput): Promise<void> {
  await rm(dir, { recursive: true, force: true });
  await mkdir(join(dir, 'projects'), { recursive: true });

  await writeFile(join(dir, 'index.json'), JSON.stringify(output.index, null, 2) + '\n');
  for (const detail of output.details) {
    await writeFile(join(dir, 'projects', `${detail.slug}.json`), JSON.stringify(detail) + '\n');
  }
  await writeFile(join(dir, 'project-loaders.ts'), projectLoadersSource(output.details.map((d) => d.slug)));

  // Routes for prerendering (used in Phase 4).
  const routes = output.index.projects.map((p) => `/work/${p.slug}`).join('\n');
  await writeFile(join(dir, 'routes.txt'), routes + '\n');
}
